import {getRawDb} from '@/db';
import {fail,isAdmin,sameOrigin,fields} from '@/lib/server';
export async function PATCH(req:Request,ctx:{params:Promise<{id:string}>}){try{
 if(!sameOrigin(req)||!await isAdmin(req))return Response.json({error:'Войдите в кабинет'},{status:401});
 const {id}=await ctx.params;const b=await req.json() as Record<string,unknown>;const stamp=Number(b.editStamp);delete b.editStamp;const entries=Object.entries(b);if(!Number.isFinite(stamp)||entries.length!==1)return Response.json({error:'Недопустимый запрос'},{status:400});if(!entries.length||entries.some(([k])=>!fields[k]))return Response.json({error:'Недопустимое поле'},{status:400});
 const values=entries.map(([k,v])=>{if(['lastName','firstName','phone'].includes(k)){if(typeof v!=='string'||v.length>80)throw Error('invalid');return v;}if(v===null||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0||n>1000||(['bench','pullups'].includes(k)&&!Number.isInteger(n))||(['bodyWeight','barWeight','swimSeconds'].includes(k)&&n===0))throw Error('invalid');return n;});
 const result=await getRawDb().prepare(`UPDATE participants SET ${entries.map(([k])=>fields[k]+' = ?').join(', ')}, updated_at = ?, field_times = json_set(field_times, ?, ?) WHERE id = ? AND COALESCE(json_extract(field_times, ?), 0) <= ?`).bind(...values,new Date().toISOString(),'$.'+entries[0][0],stamp,id,'$.'+entries[0][0],stamp).run();
 if(!result.meta.changes){const exists=await getRawDb().prepare('SELECT id FROM participants WHERE id = ?').bind(id).first();if(!exists)return Response.json({error:'Участник не найден'},{status:404});}return Response.json({ok:true});
 }catch(e){if(e instanceof Error&&e.message==='invalid')return Response.json({error:'Проверьте данные: вес и время заплыва больше нуля, повторы — целое число от 0 до 1000.'},{status:400});return fail(e);}}
