'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Dumbbell,MapPin,Check,LockKeyhole,Trophy,LoaderCircle} from 'lucide-react';
import Link from 'next/link';
export function Brand(){return <Link href="/" className="brand"><span>РЕПАБЛИКА<span className="brand-dot">.</span></span><small>ФИТНЕС · НОВОГОРСК</small></Link>;}
export default function Home(){
 const [success,setSuccess]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const formRef=useRef<HTMLFormElement>(null);
 async function register(data:{lastName:string;firstName:string;phone:string}){setBusy(true);setError('');try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error);setSuccess(true);return {registered:true};}catch(e){setError(e instanceof Error?e.message:'Не удалось отправить заявку');throw e;}finally{setBusy(false);}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'register_marathon_participant',title:'Зарегистрироваться на кубок',description:'Register a participant with surname, first name and mobile phone, and show confirmation.',inputSchema:{type:'object',properties:{lastName:{type:'string'},firstName:{type:'string'},phone:{type:'string'}},required:['lastName','firstName','phone'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const b=input as Record<string,unknown>;if(!b||typeof b.lastName!=='string'||typeof b.firstName!=='string'||typeof b.phone!=='string')throw Error('Укажите фамилию, имя и телефон');return register(b as {lastName:string;firstName:string;phone:string});}},{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e);}return()=>lifecycle.abort();},[]);
 return <><header className="site-header"><div className="container header-inner"><Brand/><span className="header-address">Олимпийская, 15</span><Button className="header-cta" asChild><a href="#participate">Хочу участвовать</a></Button></div></header>
 <main><section className="hero"><div className="hero-photo"/><div className="container hero-inner"><div className="event-label"><span className="label-line"/>17 · 19 · 20 · 21 ОКТЯБРЯ 2026</div><h1>КУБОК<br/><span>РЕПАБЛИКИ</span><br/>ФИТНЕС</h1><p className="hero-description">Четыре дисциплины.<br/>Твой собственный результат.</p><Button className="primary-cta" asChild><a href="#participate">Хочу участвовать</a></Button><p className="hero-location"><MapPin size={17}/>Репаблика фитнес · Новогорск</p></div><div className="hero-caption">ТРЕНАЖЁРНЫЙ ЗАЛ · ОЛИМПИЙСКАЯ, 15</div></section>
 <section className="dates container" aria-label="Даты кубка"><p className="date-line">17 · 19 · 20 · 21 октября</p></section>
 <section className="disciplines container"><p className="eyebrow">ПРОГРАММА КУБКА</p><h2>Соревновательные упражнения</h2><Accordion type="multiple" className="exercise-accordion">{[
  {number:'01',name:'Жим штанги лёжа',rules:['Подойдите к любому свободному тренеру тренажёрного зала: попросите подстраховать вас и зафиксировать результат. Перед упражнением разомнитесь.','Перед выполнением взвесьтесь в присутствии тренера клуба. Мужчины жмут штангу весом, равным собственному весу, женщины — половине собственного веса. В обоих случаях результат — максимальное количество повторений.','Опускайте штангу до касания грудной клетки и выжимайте её до полного выпрямления рук.']},
  {number:'02',name:'Подтягивания / отжимания от пола',rules:['Подойдите к любому свободному тренеру тренажёрного зала. Разомнитесь и попросите тренера зафиксировать количество повторений.','Мужчины выполняют подтягивания на перекладине на максимальное количество повторений. В нижней позиции руки должны быть почти полностью выпрямлены; в верхней — глаза выше уровня перекладины.','Женщины выполняют отжимания от пола на максимальное количество повторений.']},
  {number:'03',name:'Бассейн — 50 м',rules:['Мужчины и женщины плывут 50 м вольным стилем на время.','Подойдите к любому тренеру бассейна и попросите засечь время. Он внесёт результат в приложение.']},
  {number:'04',name:'Кистевая сила — динамометр',rules:['Обратитесь к тренеру Сергею: у него находится электронный динамометр. Он измерит силу хвата и внесёт результат в приложение.','Сожмите кистевой силовой динамометр одной рукой с максимальным усилием.','По две попытки каждой рукой. Засчитывается лучший результат в килограммах.']}
 ].map(d=><AccordionItem className="exercise-card" value={d.number} key={d.number}><AccordionTrigger className="exercise-trigger"><span className="exercise-heading"><span className="exercise-number">{d.number}</span><Dumbbell size={26} strokeWidth={1.5}/><span className="exercise-name">{d.name}</span><span className="exercise-hint">Описание и правила</span></span></AccordionTrigger><AccordionContent className="exercise-content">{(d.number==='01'||d.number==='03'||d.number==='04')&&<img className="discipline-photo" src={d.number==='01'?'/bench-press.jpg':d.number==='03'?'/club-pool.jpg':'/grip-dynamometer.jpg'} alt={d.number==='01'?'Жим штанги лёжа в клубе Репаблика Фитнес':d.number==='03'?'Бассейн клуба Репаблика Фитнес':'Рука с кистевым силовым динамометром'} loading="lazy"/>}<ul className="discipline-rules">{d.rules.map(rule=><li key={rule}>{rule}</li>)}</ul><p className="discipline-record">17, 19, 20 и 21 октября — в любое удобное время, когда работают тренеры. Результаты — в <Link href="/results">актуальной таблице</Link>. Мужчины и женщины оцениваются отдельно. Итоги — 22 октября.</p></AccordionContent></AccordionItem>)}</Accordion>
 <div className="cup-information"><Accordion type="multiple" className="information-accordion"><AccordionItem value="cup-rules" className="information-card"><AccordionTrigger className="information-trigger">Правила Кубка Репаблики Фитнес</AccordionTrigger><AccordionContent className="information-content"><ol>
  <li>17, 19, 20 и 21 октября проходите одну или несколько дисциплин в любое удобное время, когда работают тренеры. Можно выполнить всё за один день или распределить по дням.</li>
  <li>Перед стартом взвесьтесь в тренажёрном зале в присутствии тренера. Вес нужен для расчёта нагрузки в жиме лёжа: мужчины жмут собственный вес, женщины — половину. Перед упражнениями разомнитесь.</li>
  <li>Жим лёжа, подтягивания для мужчин и отжимания от пола для женщин — с любым свободным тренером тренажёрного зала. Попросите подстраховать вас и зафиксировать результат.</li>
  <li>Кистевая сила — у тренера Сергея, у которого находится электронный динамометр. Плавание 50 м вольным стилем — с любым тренером бассейна: попросите его засечь время.</li>
  <li>Тренер внесёт ваш вес и результаты в приложение. Свои показатели и место среди участников смотрите в <Link href="/results">актуальной таблице результатов</Link>. Мужчины и женщины оцениваются отдельно.</li>
  <li>Итоги объявим в четверг, 22 октября.</li>
 </ol></AccordionContent></AccordionItem><AccordionItem value="scoring" className="information-card"><AccordionTrigger className="information-trigger">Оценка и начисление баллов</AccordionTrigger><AccordionContent className="information-content"><ul>
  <li>Жим лёжа, подтягивания и отжимания от пола — количество повторений: больше — лучше.</li>
  <li>Плавание 50 м — время в секундах: меньше — лучше.</li>
  <li>Кистевая сила — лучший результат в килограммах: больше — лучше.</li>
  <li>Мужчины и женщины оцениваются отдельно.</li>
 </ul><p className="scoring-note">Порядок начисления баллов и определения общего места уточняется. Правила будут опубликованы здесь до начала Кубка.</p></AccordionContent></AccordionItem></Accordion></div></section>
 <section className="registration-section" id="participate"><div className="container registration-layout"><div className="registration-copy"><p className="eyebrow">17 · 19 · 20 · 21 ОКТЯБРЯ</p><h2>Твой выход.<br/><span>Твоя сила.</span></h2><p>Запишись на кубок.<br/>Организатор свяжется с тобой<br/>по мобильному телефону.</p><div className="registration-address"><MapPin size={20}/><div>Репаблика фитнес<small>Химки, Новогорск, Олимпийская, 15</small></div></div></div><div className="registration-card">{success?<div className="success-box" role="status"><span className="success-icon"><Check size={32}/></span><h3>Ты в списке!</h3><p>Заявка получена. Организатор свяжется с тобой по указанному телефону.</p><Button variant="outline" onClick={()=>{setSuccess(false);formRef.current?.reset();}}>Записать ещё участника</Button></div>:<><h3>Хочу участвовать</h3><p className="form-intro">Оставь свои контакты</p><form ref={formRef} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await register({lastName:String(f.get('lastName')),firstName:String(f.get('firstName')),phone:String(f.get('phone'))});}catch{}}}><div className="form-field"><Label htmlFor="lastName">Фамилия</Label><Input id="lastName" name="lastName" autoComplete="family-name" placeholder="Иванов" required maxLength={80}/></div><div className="form-field"><Label htmlFor="firstName">Имя</Label><Input id="firstName" name="firstName" autoComplete="given-name" placeholder="Иван" required maxLength={80}/></div><div className="form-field"><Label htmlFor="phone">Мобильный телефон</Label><Input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" placeholder="+7 (___) ___-__-__" required maxLength={25}/></div>{error&&<p className="error" role="alert">{error}</p>}<Button className="form-submit" disabled={busy}>{busy?<><LoaderCircle className="spin"/>Отправляем…</>:'Участвовать в кубке'}</Button><p className="form-note">Отправляя заявку, ты разрешаешь организатору использовать эти данные для связи по вопросам кубка.</p></form></>}</div></div></section></main>
 <footer><div className="container footer-inner"><Brand/><span>Кубок Репаблики Фитнес · Октябрь 2026</span><div className="footer-actions"><a className="organizer-button results-button" href="/results"><Trophy size={18}/>Результаты участников</a><a className="organizer-button" href="/admin"><LockKeyhole size={18}/>Кабинет организатора</a></div></div></footer></>;
}
