'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Dumbbell,MapPin,Check,LockKeyhole,Trophy,LoaderCircle} from 'lucide-react';
import Link from 'next/link';
export function Brand(){return <Link href="/" className="brand"><span>РЕСПУБЛИКА<span className="brand-dot">.</span></span><small>ФИТНЕС · НОВОГОРСК</small></Link>;}
export default function Home(){
 const [success,setSuccess]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const formRef=useRef<HTMLFormElement>(null);
 async function register(data:{lastName:string;firstName:string;phone:string}){setBusy(true);setError('');try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error);setSuccess(true);return {registered:true};}catch(e){setError(e instanceof Error?e.message:'Не удалось отправить заявку');throw e;}finally{setBusy(false);}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'register_marathon_participant',title:'Зарегистрироваться на марафон',description:'Register a participant with surname, first name and mobile phone, and show confirmation.',inputSchema:{type:'object',properties:{lastName:{type:'string'},firstName:{type:'string'},phone:{type:'string'}},required:['lastName','firstName','phone'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const b=input as Record<string,unknown>;if(!b||typeof b.lastName!=='string'||typeof b.firstName!=='string'||typeof b.phone!=='string')throw Error('Укажите фамилию, имя и телефон');return register(b as {lastName:string;firstName:string;phone:string});}},{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e);}return()=>lifecycle.abort();},[]);
 return <><header className="site-header"><div className="container header-inner"><Brand/><span className="header-address">Олимпийская, 15</span><Button className="header-cta" asChild><a href="#participate">Хочу участвовать</a></Button></div></header>
 <main><section className="hero"><div className="hero-photo"/><div className="container hero-inner"><div className="event-label"><span className="label-line"/>17 · 19 · 20 · 21 ОКТЯБРЯ 2026</div><h1>СИЛОВОЙ<br/><span>МАРАФОН</span></h1><p className="hero-description">Три дисциплины.<br/>Твой собственный результат.</p><Button className="primary-cta" asChild><a href="#participate">Хочу участвовать</a></Button><p className="hero-location"><MapPin size={17}/>Республика фитнес · Новогорск</p></div><div className="hero-caption">ТРЕНАЖЁРНЫЙ ЗАЛ · ОЛИМПИЙСКАЯ, 15</div></section>
 <section className="dates container" aria-label="Даты марафона"><div className="date-intro">ЧЕТЫРЕ ДНЯ<br/><strong>ДЛЯ ТВОЕЙ СИЛЫ</strong></div>{[['17','Суббота'],['19','Понедельник'],['20','Вторник'],['21','Среда']].map(([day,label])=><div className="date-item" key={day}><span>{day}</span><div><strong>октября</strong><small>{label}</small></div></div>)}</section>
 <section className="disciplines container"><p className="eyebrow">ПРОГРАММА МАРАФОНА</p><h2>Соревновательные упражнения</h2><Accordion type="multiple" className="exercise-accordion">{[
  {number:'01',name:'Жим штанги лёжа',rules:['Перед выполнением взвесьтесь в присутствии тренера клуба. Мужчины жмут штангу весом, равным собственному весу, женщины — половине собственного веса. В обоих случаях результат — максимальное количество повторений.','Опускайте штангу до касания грудной клетки и выжимайте её до полного выпрямления рук.']},
  {number:'02',name:'Подтягивания / отжимания от пола',rules:['Мужчины выполняют подтягивания на перекладине на максимальное количество повторений. В нижней позиции руки должны быть почти полностью выпрямлены; в верхней — глаза выше уровня перекладины.','Женщины выполняют отжимания от пола на максимальное количество повторений.']},
  {number:'03',name:'Бассейн — 50 м',rules:['Мужчины и женщины плывут 50 м вольным стилем на время.','Время прохождения дистанции фиксирует тренер.']}
 ].map(d=><AccordionItem className="exercise-card" value={d.number} key={d.number}><AccordionTrigger className="exercise-trigger"><span className="exercise-heading"><span className="exercise-number">{d.number}</span><Dumbbell size={26} strokeWidth={1.5}/><span className="exercise-name">{d.name}</span><span className="exercise-hint">Описание и правила</span></span></AccordionTrigger><AccordionContent className="exercise-content"><ul className="discipline-rules">{d.rules.map(rule=><li key={rule}>{rule}</li>)}</ul><p className="discipline-record">{d.number==='03'?'Результат — время в секундах.':'Выполните максимальное количество повторений. Результат записывает тренер.'}</p></AccordionContent></AccordionItem>)}</Accordion>
 <div className="marathon-rules" aria-labelledby="marathon-rules-title"><h3 id="marathon-rules-title">Правила марафона</h3><ol>
  <li>Участвуют мужчины и женщины. Их результаты оцениваются отдельно.</li>
  <li>Все дисциплины доступны 17, 19, 20 и 21 октября в любое удобное время, когда работают тренеры. Можно выполнить всё за один день или распределить по дням.</li>
  <li>Перед стартом разомнитесь. Когда будете готовы, подойдите к любому свободному тренеру: попросите подстраховать вас и зафиксировать результаты.</li>
 </ol></div></section>
 <section className="registration-section" id="participate"><div className="container registration-layout"><div className="registration-copy"><p className="eyebrow">17 · 19 · 20 · 21 ОКТЯБРЯ</p><h2>Твой выход.<br/><span>Твоя сила.</span></h2><p>Запишись на марафон.<br/>Организатор свяжется с тобой<br/>по мобильному телефону.</p><div className="registration-address"><MapPin size={20}/><div>Республика фитнес<small>Химки, Новогорск, Олимпийская, 15</small></div></div></div><div className="registration-card">{success?<div className="success-box" role="status"><span className="success-icon"><Check size={32}/></span><h3>Ты в списке!</h3><p>Заявка получена. Организатор свяжется с тобой по указанному телефону.</p><Button variant="outline" onClick={()=>{setSuccess(false);formRef.current?.reset();}}>Записать ещё участника</Button></div>:<><h3>Хочу участвовать</h3><p className="form-intro">Оставь свои контакты</p><form ref={formRef} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await register({lastName:String(f.get('lastName')),firstName:String(f.get('firstName')),phone:String(f.get('phone'))});}catch{}}}><div className="form-field"><Label htmlFor="lastName">Фамилия</Label><Input id="lastName" name="lastName" autoComplete="family-name" placeholder="Иванов" required maxLength={80}/></div><div className="form-field"><Label htmlFor="firstName">Имя</Label><Input id="firstName" name="firstName" autoComplete="given-name" placeholder="Иван" required maxLength={80}/></div><div className="form-field"><Label htmlFor="phone">Мобильный телефон</Label><Input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" placeholder="+7 (___) ___-__-__" required maxLength={25}/></div>{error&&<p className="error" role="alert">{error}</p>}<Button className="form-submit" disabled={busy}>{busy?<><LoaderCircle className="spin"/>Отправляем…</>:'Участвовать в марафоне'}</Button><p className="form-note">Отправляя заявку, ты разрешаешь организатору использовать эти данные для связи по вопросам марафона.</p></form></>}</div></div></section></main>
 <footer><div className="container footer-inner"><Brand/><span>Силовой марафон · Октябрь 2026</span><div className="footer-actions"><a className="organizer-button results-button" href="/results"><Trophy size={18}/>Результаты участников</a><a className="organizer-button" href="/admin"><LockKeyhole size={18}/>Кабинет организатора</a></div></div></footer></>;
}
